export enum MissionCategoryNameEnum {
  COMPLETE_LESSON_WITH_PERCENTAGE_SCORE = "COMPLETE_LESSON_WITH_PERCENTAGE_SCORE",
  COMPLETE_LESSON_WITH_DIFFERENT_SKILLS = "COMPLETE_LESSON_WITH_DIFFERENT_SKILLS",
  TOTAL_DURATION_OF_LEARN_DAILY_LESSON = "TOTAL_DURATION_OF_LEARN_DAILY_LESSON",
  EXCEED_LEARNING_STREAK_WITHOUT_BREAK = "EXCEED_LEARNING_STREAK_WITHOUT_BREAK",
  COMPLETE_A_SESSION = "COMPLETE_A_SESSION",
  COMPLETE_DISTINCT_SKILL_SESSION = "COMPLETE_DISTINCT_SKILL_SESSION",
  COMPLETE_DISTINCT_SKILL_TEST_SESSION = "COMPLETE_DISTINCT_SKILL_TEST_SESSION",
}
