export enum MissionNameEnum {
  COMPLETE_LESSON_PERFECTLY = "COMPLETE_LESSON_PERFECTLY",
  COMPLETE_LESSON_WITH_PERCENTAGE_SCORE = "COMPLETE_LESSON_WITH_PERCENTAGE_SCORE",
  EXCEED_STREAK = "EXCEED_STREAK",
}
