export enum MissionCategoryNameEnum {
  COMPLETE_LESSON_WITH_PERCENTAGE_SCORE = "COMPLETE_LESSON_WITH_PERCENTAGE_SCORE",
  COMPLETE_LESSON_WITH_DIFFERENT_SKILLS = "COMPLETE_LESSON_WITH_DIFFERENT_SKILLS",
  TOTAL_DURATION_OF_LEARN_DAILY_LESSON = "TOTAL_DURATION_OF_LEARN_DAILY_LESSON",
  EXCEED_LEARNING_STREAK = "EXCEED_LEARNING_STREAK",
  EXCEED_LEARNING_STREAK_WITHOUT_BREAK = "EXCEED_LEARNING_STREAK_WITHOUT_BREAK",
  COMPLETE_LISTENING_SESSION = "COMPLETE_LISTENING_SESSION",
  COMPLETE_READING_SESSION = "COMPLETE_READING_SESSION",
  COMPLETE_SPEAKING_SESSION = "COMPLETE_SPEAKING_SESSION",
  COMPLETE_WRITING_SESSION = "COMPLETE_WRITING_SESSION",
  COMPLETE_DISTINCT_SKILL_SESSION = "COMPLETE_DISTINCT_SKILL_SESSION",
  COMPLETE_DISTINCT_SKILL_TEST_SESSION = "COMPLETE_DISTINCT_SKILL_TEST_SESSION",
}
