services:
  main-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
      args:
        SERVICE_NAME: main-api
        STAGE: dev
    env_file:
      - .env
    ports:
      - "4000:3000"
    container_name: main-service
    networks:
      - ll-network

networks:
  ll-network:
    driver: bridge