services:
  postgres:
    image: postgres:16.0
    container_name: postgres
    env_file:
      - stack.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - ll-network

  redis:
    image: redis:6
    container_name: redis
    env_file:
      - stack.env
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - ll-network

  main-api:
    image: ${IMAGE_NAME}:${IMAGE_TAG-:stable}
    env_file:
      - stack.env
    ports:
      - "3000:3000"
    container_name: main-api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    networks:
      - ll-network

volumes:
  postgres-data:
    name: postgres-data
  redis-data:
    name: redis-data
networks:
  ll-network:
    driver: bridge
