services:
  migration:
    build:
      context: .
      dockerfile: docker/Dockerfile.migration
    env_file:
      - .env.prod
    container_name: migration
    restart: "no"

  main-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    container_name: main-api
    depends_on:
      migration:
        condition: service_completed_successfully
    restart: always
