export const QUEST_HANDLERS_MAP = "QUEST_HANDLERS_MAP";
export const EXCEED_LEARNING_STREAK_PROVIDER = "EXCEED_LEARNING_STREAK_PROVIDER";
export const EXCEED_LEARNING_STREAK_WITHOUT_BREAK_PROVIDER = "EXCEED_LEARNING_STREAK_WITHOUT_BREAK_PROVIDER";
export const COMPLETE_SPEAKING_SESSION_PROVIDER = "COMPLETE_SPEAKING_SESSION_PROVIDER";
export const COMPLETE_LISTENING_SESSION_PROVIDER = "COMPLETE_LISTENING_SESSION_PROVIDER";
export const COMPLETE_READING_SESSION_PROVIDER = "COMPLETE_READING_SESSION_PROVIDER";
export const COMPLETE_WRITING_SESSION_PROVIDER = "COMPLETE_WRITING_SESSION_PROVIDER";

export const MISSION_SUBJECT_FACTORY = "MISSION_SUBJECT_FACTORY";
export const LEARNER_SUBJECT_FACTORY = "LEARNER_SUBJECT_FACTORY";
