name: CD

on:
  workflow_dispatch:

jobs:
  push-image:
    name: Push Image To Docker Registry
    runs-on: ubuntu-latest

    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Set up Docker Buildx cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Fetch .env file
        run: |
          curl -H "Authorization: token ${{ secrets.PRIVATE_TOKEN }}" \
          -o .env https://raw.githubusercontent.com/Lapin-Learn/env/main/backend/${{ VARS.STAGE }}/.env

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        id: docker_build_main_api
        with:
          context: ./
          file: ./docker/Dockerfile.service
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/backend-main-server:${{VARS.STAGE}}-${{github.sha}}
            ${{ secrets.DOCKER_USERNAME }}/backend-main-server:${{VARS.STAGE}}-latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/backend-main-server:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/backend-main-server:cache,mode=max

  deploy-staging:
    name: Deploy Staging
    if: github.ref != 'refs/heads/main'
    uses: Lapin-Learn/backend-main-server/.github/workflows/deploy-staging.yml@develop
    secrets: inherit

  deploy-prod:
    name: Deploy Production
    if: github.ref == 'refs/heads/main'
    uses: Lapin-Learn/backend-main-server/.github/workflows/deploy-prod.yml@main
    secrets: inherit
