name: Deploy Image

on:
  workflow_run:
    workflows: ["push image"]
    types:
      - completed

jobs:
  deploy_dev:
    if: ${{ github.event.workflow_run.head_branch == 'develop' }}
    uses: Lapin-Learn/backend-main-server/.github/workflows/deploy-staging.yml@develop

  deploy_prod:
    if: ${{ github.event.workflow_run.head_branch == 'main' }}
    uses: Lapin-Learn/backend-main-server/.github/workflows/deploy-prod.yml@main
