name: Deploy To Production environment

on:
  workflow_call:

jobs:
  deploy:
    name: Push New commit To Infrastructure Repo
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Infrastructure Repo
        uses: actions/checkout@v4
        with:
          repository: Lapin-Learn/infrastructure
          token: ${{ secrets.PRIVATE_TOKEN }}
          fetch-depth: 0

      - name: Modify Image Tag
        run: |
          NEW_IMAGE_TAG=${{VARS.STAGE}}-${{ github.sha }}
          sed -i "s|image: duyquan/backend-main-server:.*|image: duyquan/backend-main-server:$NEW_IMAGE_TAG|" k8s/be-deployment.yml

      - name: Commit and Push Changes
        run: |
          NEW_IMAGE_TAG=${{VARS.STAGE}}-${{ github.sha }}
          git config --global user.name "Quan0308"
          git config --global user.email "bddquan@gmail.com"
          git add k8s/be-deployment.yml
          git commit -m "chore: Update backend deployment image with tag $NEW_IMAGE_TAG"
          git push origin main
