name: Deploy image

on:
  workflow_dispatch:
jobs:
  deploy-image:
    name: Deploy server image
    runs-on: ubuntu-latest

    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        env:
          TAG: ${{VARS.TAG}}
        run: |
          docker build -f docker/Dockerfile.service -t ${{secrets.DOCKER_USERNAME}}/backend-main-server:$TAG .

      - name: Push Docker image
        env:
          TAG: ${{VARS.TAG}}
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/backend-main-server:$TAG
