name: Deploy image

on:
  workflow_dispatch:
jobs:
  deploy-image:
    name: Deploy server image
    runs-on: ubuntu-latest

    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Set up Docker Buildx cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        id: docker_build_main_api
        with:
          context: ./
          file: ./docker/Dockerfile.service
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            PRIVATE_TOKEN=${{secrets.PRIVATE_TOKEN}}
            STAGE=${{VARS.STAGE}}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/backend-main-server:${{github.sha}}
            ${{ secrets.DOCKER_USERNAME }}/backend-main-server:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/backend-main-server:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/backend-main-server:cache,mode=max

      - name: Workflow Webhook Action
        uses: distributhor/workflow-webhook@v3.0.7
        with:
          webhook_url: ${{secrets.WEBHOOK_URL}}?IMAGE_TAG=${{github.sha}}
          verbose: false
          max_time: 360
          verify_ssl: false
